import express from 'express';
import cors from 'cors';
import bcrypt from 'bcryptjs';
import 'dotenv/config';
import { pool } from './db.js';
import { tokenFor, requireAuth, requireAdmin } from './auth.js';

const app = express();
app.use(cors()); app.use(express.json());
const today = () => new Date().toISOString().slice(0, 10);
const ok = (res, data) => res.json(data);

app.get('/health', (_, res) => ok(res, { status: 'ok', service: 'centro-diurno-api' }));

app.post('/api/auth/login', async (req, res) => {
  const { username, password } = req.body;
  const [rows] = await pool.query('SELECT * FROM users WHERE username=?', [username]);
  if (!rows[0] || !(await bcrypt.compare(password || '', rows[0].password_hash))) return res.status(401).json({ message: 'Credenziali non valide' });
  ok(res, { token: tokenFor(rows[0]), user: { id: rows[0].id, username: rows[0].username, fullName: rows[0].full_name, role: rows[0].role, points: rows[0].total_points } });
});

app.get('/api/admin/users', requireAuth, requireAdmin, async (_, res) => { const [r] = await pool.query("SELECT u.id,u.username,u.full_name AS fullName,u.total_points AS points,u.created_at AS createdAt,g.target_points AS targetPoints FROM users u LEFT JOIN user_goals g ON g.user_id=u.id WHERE u.role='USER' ORDER BY u.full_name"); ok(res,r); });
app.post('/api/admin/users', requireAuth, requireAdmin, async (req,res) => {
  const { username, password, fullName } = req.body;
  if (!username || !password || !fullName) return res.status(400).json({ message:'username, password e fullName sono obbligatori' });
  const conn=await pool.getConnection();
  try { await conn.beginTransaction(); const [r] = await conn.query('INSERT INTO users (username,password_hash,full_name) VALUES (?,?,?)',[username,await bcrypt.hash(password,10),fullName]); await conn.query("INSERT INTO user_goals(user_id,title,target_points) VALUES (?, 'Traguardo', 100)",[r.insertId]); await conn.commit(); res.status(201).json({ id:r.insertId, username, fullName, targetPoints:100 }); }
  catch (e) { await conn.rollback(); res.status(e.code==='ER_DUP_ENTRY'?409:500).json({ message:'Impossibile creare l’utente' }); }
  finally { conn.release(); }
});

async function requireUserId(userId) {
  const [[user]] = await pool.query("SELECT id FROM users WHERE id=? AND role='USER'", [userId]);
  return user?.id;
}
app.get('/api/admin/moods', requireAuth, requireAdmin, async (_,res)=>{ const [r]=await pool.query("SELECT m.id,m.name,m.points,m.active,um.user_id AS userId,u.full_name AS userName FROM moods m JOIN user_moods um ON um.mood_id=m.id JOIN users u ON u.id=um.user_id ORDER BY m.id DESC"); ok(res,r); });
app.post('/api/admin/moods', requireAuth, requireAdmin, async (req,res)=>{ const {name,points,userId}=req.body; if(!name || !(await requireUserId(userId))) return res.status(400).json({message:'Nome e utente destinatario sono obbligatori'}); const conn=await pool.getConnection(); try { await conn.beginTransaction(); const [r]=await conn.query('INSERT INTO moods(name,points) VALUES (?,?)',[name,Number(points)||0]); await conn.query('INSERT INTO user_moods(user_id,mood_id) VALUES (?,?)',[userId,r.insertId]); await conn.commit(); res.status(201).json({id:r.insertId,name,points:Number(points)||0,userId}); } catch(e) { await conn.rollback(); res.status(500).json({message:'Impossibile creare lo stato d’animo'}); } finally { conn.release(); } });
app.delete('/api/admin/moods/:id', requireAuth, requireAdmin, async (req,res)=>{ const [r]=await pool.query('UPDATE moods SET active=FALSE WHERE id=? AND active=TRUE',[req.params.id]); if(!r.affectedRows) return res.status(404).json({message:'Stato d’animo non trovato'}); res.status(204).end(); });
app.get('/api/admin/activities', requireAuth, requireAdmin, async (_,res)=>{ const [r]=await pool.query("SELECT a.id,a.title,a.description,a.points,a.active,ua.user_id AS userId,u.full_name AS userName FROM activities a JOIN user_activities ua ON ua.activity_id=a.id JOIN users u ON u.id=ua.user_id ORDER BY a.id DESC"); ok(res,r); });
app.post('/api/admin/activities', requireAuth, requireAdmin, async (req,res)=>{ const {title,description,points,userId}=req.body; if(!title || !(await requireUserId(userId))) return res.status(400).json({message:'Titolo e utente destinatario sono obbligatori'}); const conn=await pool.getConnection(); try { await conn.beginTransaction(); const [r]=await conn.query('INSERT INTO activities(title,description,points) VALUES (?,?,?)',[title,description||'',Number(points)||0]); await conn.query('INSERT INTO user_activities(user_id,activity_id) VALUES (?,?)',[userId,r.insertId]); await conn.commit(); res.status(201).json({id:r.insertId,title,description:description||'',points:Number(points)||0,userId}); } catch(e) { await conn.rollback(); res.status(500).json({message:'Impossibile creare l’attività'}); } finally { conn.release(); } });
app.delete('/api/admin/activities/:id', requireAuth, requireAdmin, async (req,res)=>{ const [r]=await pool.query('UPDATE activities SET active=FALSE WHERE id=? AND active=TRUE',[req.params.id]); if(!r.affectedRows) return res.status(404).json({message:'Attività non trovata'}); res.status(204).end(); });
app.put('/api/admin/users/:id/goal', requireAuth, requireAdmin, async (req,res)=>{ const targetPoints=Number(req.body.targetPoints); if(!Number.isFinite(targetPoints) || targetPoints<=0 || !(await requireUserId(req.params.id))) return res.status(400).json({message:'Utente e punteggio massimo valido sono obbligatori'}); await pool.query("INSERT INTO user_goals(user_id,title,target_points) VALUES (?, 'Traguardo', ?) ON DUPLICATE KEY UPDATE target_points=VALUES(target_points)",[req.params.id,targetPoints]); ok(res,{userId:Number(req.params.id),title:'Traguardo',targetPoints}); });
app.get('/api/admin/pending', requireAuth, requireAdmin, async (_,res)=>{ const [checkins]=await pool.query("SELECT c.id,c.checkin_date AS date,u.full_name AS userName FROM checkins c JOIN users u ON u.id=c.user_id WHERE c.status='PENDING' ORDER BY c.id"); const [moods]=await pool.query("SELECT m.id,m.created_at AS createdAt,u.full_name AS userName,mo.name,mo.points FROM mood_entries m JOIN users u ON u.id=m.user_id JOIN moods mo ON mo.id=m.mood_id WHERE m.status='PENDING' ORDER BY m.id"); const [activities]=await pool.query("SELECT ae.id,ae.activity_date AS date,u.full_name AS userName,a.title,ae.points_snapshot AS points FROM activity_entries ae JOIN users u ON u.id=ae.user_id JOIN activities a ON a.id=ae.activity_id WHERE ae.status='PENDING' ORDER BY ae.id"); ok(res,{checkins,moods,activities}); });
app.get('/api/admin/checkins/history', requireAuth, requireAdmin, async (_,res)=>{ const [r]=await pool.query("SELECT c.id,c.checkin_date AS date,c.status,c.approved_at AS approvedAt,u.full_name AS userName FROM checkins c JOIN users u ON u.id=c.user_id ORDER BY c.checkin_date DESC,c.id DESC"); ok(res,r); });
app.post('/api/admin/checkins/:id/approve', requireAuth, requireAdmin, async (req,res)=>{ await pool.query("UPDATE checkins SET status='APPROVED',approved_at=NOW() WHERE id=? AND status='PENDING'",[req.params.id]); ok(res,{message:'Check-in approvato'}); });
app.post('/api/admin/moods/:id/approve', requireAuth, requireAdmin, async (req,res)=>{ const conn=await pool.getConnection(); try { await conn.beginTransaction(); const [r]=await conn.query("SELECT user_id,mood_id FROM mood_entries WHERE id=? AND status='PENDING' FOR UPDATE",[req.params.id]); if(!r[0]) return res.status(404).json({message:'Richiesta non trovata'}); await conn.query("UPDATE mood_entries SET status='APPROVED',points_awarded=TRUE,approved_at=NOW() WHERE id=?",[req.params.id]); await conn.query('UPDATE users u JOIN moods m ON m.id=? SET u.total_points=u.total_points+m.points WHERE u.id=?',[r[0].mood_id,r[0].user_id]); await conn.commit(); ok(res,{message:'Stato d’animo approvato'}); } catch(e){await conn.rollback();res.status(500).json({message:'Errore approvazione'});} finally{conn.release();} });
app.post('/api/admin/activities/:id/approve', requireAuth, requireAdmin, async (req,res)=>{ const conn=await pool.getConnection(); try { await conn.beginTransaction(); const [r]=await conn.query("SELECT user_id,points_snapshot FROM activity_entries WHERE id=? AND status='PENDING' FOR UPDATE",[req.params.id]); if(!r[0]) { await conn.rollback(); return res.status(404).json({message:'Richiesta attività non trovata'}); } await conn.query("UPDATE activity_entries SET status='APPROVED',points_awarded=TRUE,approved_at=NOW() WHERE id=?",[req.params.id]); await conn.query('UPDATE users SET total_points=total_points+? WHERE id=?',[r[0].points_snapshot,r[0].user_id]); await conn.commit(); ok(res,{message:'Attività approvata'}); } catch(e){await conn.rollback();res.status(500).json({message:'Errore approvazione attività'});} finally{conn.release();} });

app.get('/api/me', requireAuth, async (req,res)=>{ const [[user]] = await pool.query('SELECT id,username,full_name AS fullName,total_points AS points FROM users WHERE id=?',[req.user.id]); const [[goal]]=await pool.query("SELECT title,target_points AS targetPoints FROM user_goals WHERE user_id=?",[req.user.id]); const [activities]=await pool.query('SELECT a.id,a.title,a.description,a.points FROM activities a JOIN user_activities ua ON ua.activity_id=a.id WHERE ua.user_id=? AND a.active=TRUE',[req.user.id]); const [moods]=await pool.query('SELECT m.id,m.name,m.points FROM moods m JOIN user_moods um ON um.mood_id=m.id WHERE um.user_id=? AND m.active=TRUE',[req.user.id]); ok(res,{user,goal,activities,moods}); });
app.post('/api/me/checkins', requireAuth, async (req,res)=>{ try { const [r]=await pool.query('INSERT INTO checkins(user_id,checkin_date) VALUES (?,?)',[req.user.id,today()]); res.status(201).json({id:r.insertId,status:'PENDING'}); } catch(e){res.status(e.code==='ER_DUP_ENTRY'?409:500).json({message:'Check-in già richiesto oggi'});} });
app.post('/api/me/moods', requireAuth, async (req,res)=>{ const {moodId}=req.body; const [m]=await pool.query('SELECT m.id FROM moods m JOIN user_moods um ON um.mood_id=m.id WHERE m.id=? AND um.user_id=? AND m.active=TRUE',[moodId,req.user.id]); if(!m[0]) return res.status(404).json({message:'Stato d’animo non disponibile'}); const [r]=await pool.query('INSERT INTO mood_entries(user_id,mood_id) VALUES (?,?)',[req.user.id,moodId]); res.status(201).json({id:r.insertId,status:'PENDING'}); });
app.post('/api/me/activities/:id/complete', requireAuth, async (req,res)=>{ const [checkin]=await pool.query("SELECT id FROM checkins WHERE user_id=? AND checkin_date=? AND status='APPROVED'",[req.user.id,today()]); if(!checkin[0]) return res.status(409).json({message:'È richiesto un check-in approvato per oggi'}); const [[activity]]=await pool.query('SELECT a.id,a.points FROM activities a JOIN user_activities ua ON ua.activity_id=a.id WHERE a.id=? AND ua.user_id=? AND a.active=TRUE',[req.params.id,req.user.id]); if(!activity) return res.status(404).json({message:'Attività non disponibile'}); try { const [r]=await pool.query('INSERT INTO activity_entries(user_id,activity_id,activity_date,points_snapshot) VALUES (?,?,?,?)',[req.user.id,activity.id,today(),activity.points]); res.status(201).json({id:r.insertId,status:'PENDING'}); } catch(e) { res.status(e.code==='ER_DUP_ENTRY'?409:500).json({message:e.code==='ER_DUP_ENTRY'?'Attività già richiesta oggi':'Impossibile inviare l’attività'}); } });

app.use((err,_,res,__)=>res.status(500).json({message:err.message||'Errore interno'}));
app.listen(Number(process.env.PORT||3000),()=>console.log(`API attiva sulla porta ${process.env.PORT||3000}`));
